### ISSUE TITLE
browser compatibility

### ISSUE THREAD

**Issue by gregu4** [chiasm-project/chiasm#50]
precise the compatibilities.
for instance it doesn't seem to work with my IE11.

**Comment by curran** [comment]
Thank you for opening this. Indeed, this needs to be investigated.

Some parts of the code use `Promise`, but there is no polyfill set up. That might be causing the problem.

Could you please post the errors you get in in IE11 and which example gives rise to the errors? Thank you.

**Comment by gregu4** [comment]
I think neither work.
I've got for instance for the first example just a blank white area.
The error in the console is
« Promise » undefined

2015-10-23 3:40 GMT+02:00 Curran Kelleher notifications@github.com:

**Comment by curran** [comment]
Ok, thank you. I think this needs to be addressed by adding a Promise polyfill. I will look into this.

**Comment by curran** [comment]
I'm not sure which Promise library would be best. Does anyone have any suggestions? My preference is that it should be small, and conform to ES6 Promises. This is something that will need to be adopted in all Chiasm modules where Promises are used in order to guarantee browser compatibility. 

For reference, here's the [browser compatibility table for Promises](http://caniuse.com/#feat=promises). IE is the only major browser that doesn't support them.

**Comment by curran** [comment]
Actually, this looks like the most popular Promise polyfill library out there by far https://github.com/jakearchibald/es6-promise

**Comment by curran** [comment]
@gregu4 , I have added the es6-promise polyfill and cut a [new release, v0.3.0](https://github.com/chiasm-project/chiasm/releases/tag/v0.3.0) (published in gh-pages branch as [chiasm-v0.3.0.js](http://chiasm-project.github.io/chiasm/chiasm-v0.3.0.js)). Could you please try out this new release and let me know if you encounter more browser compatibility issues? Thank you.

Also as a side note, adding this polyfill seems to have increased the library size from 22k to 57k unminified (27k minified).

**Comment by gregu4** [comment]
great I will, thanks

2015-12-01 1:18 GMT+01:00 Curran Kelleher notifications@github.com:
